[package]
name = "war_card_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.3.0"
itertools = "0.10.5"
queues = "1.1.0"
